/**
 * RFC 7807 - Problem Details for HTTP APIs
 * https://tools.ietf.org/html/rfc7807
 */
export class ProblemDetailsDto {
  /**
   * A URI reference [RFC3986] that identifies the problem type.
   * Consumers MUST use the URI (after resolution, if necessary) as
   * the problem type's primary identifier.
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   */
  title: string;

  /**
   * The HTTP status code ([RFC7231], Section 6) generated by the
   * origin server for this occurrence of the problem.
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the
   * problem.
   */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence of the
   * problem. It may or may not yield further information if dereferenced.
   */
  instance?: string;

  /**
   * HTTP method used in the request.
   */
  method?: string;

  /**
   * Timestamp when the error occurred.
   */
  timestamp?: string;

  /**
   * Unique identifier for this error occurrence (useful for logs).
   */
  traceId?: string;

  /**
   * Additional properties specific to the problem.
   */
  [key: string]: any;
}
